name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 danger:
    name: Linting with Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
     # - uses: MeilCli/danger-action@v4
      #  with:
       #  plugins_file: '.github/Gemfile'
        # install_path: 'vendor/bundle'
         #danger_file: '.github/Dangerfile'
         #danger_id: 'danger-pr'
        #env:
         # DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - name: Build with Gradle
        run: ./gradlew runChecksForDanger
         # Run Danger
      - name: bundle install
        run: bundle install
      #- name: bundle exec danger init
       # run: bundle exec danger init   
      - name: exicute danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
